### ISSUE TITLE
Nothing interesting to see here?! (FF51)

### ISSUE THREAD

**Issue by LigH-de** [toji/webgl2-particles-2#10]
Just updated to Firefox 51.0.1 for Win32, using a normal PC with Windows 7 SP1 64b and only keyboard and mouse as input device, GeForce 9600. Read about v51 now supporting WebGL 2, so I searched for a demo and found this repo. The previous version worked well, a lot of colored particles blown by the wind... but here? Somehow I believe I only see a top half or third of a room that goes a lot deeper, but outside the window, so I can't see the particles at its bottom.

Screenshot:
![webgl2-particles-2](https://cloud.githubusercontent.com/assets/5917225/22550754/d2fcdde8-e951-11e6-81a5-200ddbd65fc3.png)

**Comment by LigH-de** [comment]
Same issue in Pale Moon 27.0.3 (which is very similar to a recent Firefox), and Vivaldi 1.7.735.27 (Chrome/56.0.2924.77).

**Comment by kenrussell** [comment]
The GeForce 9600 is only a Direct3D 10 capable GPU. Direct3D 11 support is required for WebGL 2.0 in all browsers. In Chrome, about:gpu contains this information; not sure in Firefox. CC @jdashg

**Comment by LigH-de** [comment]
If Direct3D 11 was a necessary requirement for WebGL 2.0, the project [webgl2-particles](http://toji.github.io/webgl2-particles/) would not work either; but it works fine, as far as I see. And in webgl2-particles-2, I see at least a room (I just believe that its dimensions are displayed wrong).

Now on a PC with Nvidia GTS 450:

- [webgl2-particles](http://toji.github.io/webgl2-particles/) works, the same way: Colored particles forming a text and drifting away.
- [webgl2-particles-2](http://toji.github.io/webgl2-particles-2/) does not work, the same way: Only an upper part of a room is visible to me.

**Comment by toji** [comment]
webgl2-particles has a WebGL 1 fallback, and was primarily about demonstrating how the same effect could be performed more efficiently with WebGL 2 features. webgl2-particles-2 does not contain the same fallback path because the intent was to push the simulation further, doing things that we didn't have an obvious way to achieve in WebGL 1. This includes tracking not just position but velocity at each simulation step and maintaining a random number seed per particle with integer textures.

So this appears to be WAI. We could probably stand to add an error message, though, stating that your system doesn't support WebGL 2. Also, I'd like to hear @jdashg's answer to @kenrussell's question about checking support in Firefox.

**Comment by LigH-de** [comment]
I was slightly wrong: webgl2-particles-2 works in Firefox 51, just not in Pale Moon 27. Sorry for the confusion.

Yes, a little pre-analysis output for basic debugging would possibly be useful.

**Comment by kdashg** [comment]
In Firefox, it's "about:support".
